// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9z-yADvB8OfZtBp611ikxF8sCMOAlAxg',
    appId: '1:713287241110:web:e4189745494509523021b7',
    messagingSenderId: '713287241110',
    projectId: 'ikikitomo-9cf3e',
    authDomain: 'ikikitomo-9cf3e.firebaseapp.com',
    storageBucket: 'ikikitomo-9cf3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7b4VtTF5tUZvBISCe2VmimQDAxCX0Sa4',
    appId: '1:713287241110:android:4074dfd5522148db3021b7',
    messagingSenderId: '713287241110',
    projectId: 'ikikitomo-9cf3e',
    storageBucket: 'ikikitomo-9cf3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ_ZKZVGMmfRjVXtP7Th-Ldd2qfrEJf8A',
    appId: '1:713287241110:ios:9c5474ea2e2ea38c3021b7',
    messagingSenderId: '713287241110',
    projectId: 'ikikitomo-9cf3e',
    storageBucket: 'ikikitomo-9cf3e.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ_ZKZVGMmfRjVXtP7Th-Ldd2qfrEJf8A',
    appId: '1:713287241110:ios:b2f5e3839eba5ed73021b7',
    messagingSenderId: '713287241110',
    projectId: 'ikikitomo-9cf3e',
    storageBucket: 'ikikitomo-9cf3e.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
